name: CD

on:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ci-check-format

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ci-check-format

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ci-check-cache

      - name: Install dependencies
        run: npm install

      - name: Run svelte-check
        run: npm run check

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [format, lint, build]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ci-build-cache

      - name: Install dependencies
        run: npm install

      - name: Build website
        env:
          CONTENTFUL_DELIVERY_KEY: ${{ secrets.CONTENTFUL_DELIVERY_KEY }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        run: npm run build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy website
        run: surge build uiuc.hack4impact.org
