name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ci-check-cache

      - name: Install dependencies
        run: npm install

      - name: Run svelte-check
        run: npm run validate

  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ci-build-cache

      - name: Install dependencies
        run: npm install

      - name: Build website
        env:
          CONTENTFUL_DELIVERY_KEY: ${{ secrets.CONTENTFUL_DELIVERY_KEY }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        run: npm run export
